% pcex 1.4.6
% check the normality of random values generated by the
% Box-Muller method and the Polar Marsaglia method

% 16.02.2015
% =========================================================================
v = gauss_box(-2,10E3);
histogram(v,-6:10E-2:6);
mu = sum(v) / (length(v) - 1);
var = sum((v - mu).^2) / (length(v) - 1);
title('histogram of random values generated by Box-Muller','fontsize',15)
